version: '3'

services:

  rails:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./script/start
    volumes:
      - .:/var/www/welcome-chat
    ports:
      - '3000:3000'
    links:
      - redis
      - db
    stdin_open: true
    tty: true

  redis:
    image: redis:5.0.4
    volumes:
      - redis:/var/lib/redis
    ports:
      - "6379:6379"

  db:
    image: postgres:11.2
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  redis:
  postgres:
