development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://redis:6379/1" } %>
  channel_prefix: welcome_chat_development

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:xxxxxxxx@xxxxxxxx.redistogo.com:9273/
  channel_prefix: welcome_chat_production
